Repository jupyterlab/extension-cookiecutter-ts, pull requests merged in 2022-12, with the labels that each got.

#249 Update versions of GH actions
  .github/workflows/check-tests.yml
  .github/workflows/main.yml
  {{cookiecutter.python_name}}/.github/workflows/build.yml
  {{cookiecutter.python_name}}/.github/workflows/check-release.yml
  {{cookiecutter.python_name}}/.github/workflows/update-integration-tests.yml
  {{cookiecutter.python_name}}/conftest.py
  {{cookiecutter.python_name}}/pyproject.toml
Labels: bug, maintenance

#254 Backport PR #249 on branch 3.0 (Update versions of GH actions)
  .github/workflows/check-tests.yml
  .github/workflows/main.yml
  {{cookiecutter.python_name}}/.github/workflows/build.yml
  {{cookiecutter.python_name}}/.github/workflows/check-release.yml
  {{cookiecutter.python_name}}/.github/workflows/update-integration-tests.yml
  {{cookiecutter.python_name}}/conftest.py
  {{cookiecutter.python_name}}/pyproject.toml
Labels: bug, maintenance

#262 Introduce new css variables.
  {{cookiecutter.python_name}}/style/variables.css
Labels: enhancement

#263 Backport PR #262 on branch 4.0 (Introduce new css variables.)
  {{cookiecutter.python_name}}/style/variables.css
Labels: enhancement

#265 Backport PR #264 on branch 4.0 (Add `yarn-error.log` to `.gitignore`)
  {{cookiecutter.python_name}}/.gitignore
Labels: enhancement

#255 Improve [test] template conditioning
  {{cookiecutter.python_name}}/README.md
  {{cookiecutter.python_name}}/pyproject.toml
Labels: documentation

#253 Ignore Jest coverage directory
  {{cookiecutter.python_name}}/.gitignore
Labels: bug

#268 Backport PR #253 on branch 4.0 (Ignore Jest coverage directory)
  {{cookiecutter.python_name}}/.gitignore
Labels: bug
