Repository jupyterlab/extension-cookiecutter-ts, pull requests merged in 2023-01, with the labels that each got.

#271 Upgrades binder nodejs version
  {{cookiecutter.python_name}}/binder/environment.yml
Labels: bug, maintenance

#280 Backport PR #278 on branch 3.0 (Updated default build to generate source maps)
  {{cookiecutter.python_name}}/package.json
Labels: enhancement

#279 Use `binder-link` action from `maintainer-tools`
  {{cookiecutter.python_name}}/.github/workflows/binder-on-pr.yml
Labels: maintenance

#281 Backport PR #279 on branch 4.0 (Use `binder-link` action from `maintainer-tools`)
  {{cookiecutter.python_name}}/.github/workflows/binder-on-pr.yml
Labels: maintenance
