Repository jupyterlab/extension-cookiecutter-ts, pull requests merged in 2023-03, with the labels that each got.

#290 Update to TypeScript 5
  {{cookiecutter.python_name}}/package.json
Labels: maintenance

#294 Bump the dependencies
  {{cookiecutter.python_name}}/package.json
  {{cookiecutter.python_name}}/pyproject.toml
  {{cookiecutter.python_name}}/style/index.css
  {{cookiecutter.python_name}}/ui-tests/package.json
Labels: maintenance

#297 Backport PR #296 on branch 4.0 (Add options description)
  README.md
Labels: documentation

#298 Explicit checkout option for now
  README.md
Labels: documentation

#299 Add ui-tests as workspace
  {{cookiecutter.python_name}}/package.json
Labels: bug

#300 Remove temporary fix for ui tests
  {{cookiecutter.python_name}}/ui-tests/jupyter_server_test_config.py
Labels: bug
